import React from "react";
import { Cpu, ShieldCheck, TrendingUp, AlertCircle, Info, CheckCircle2, Award, Sparkles, BarChart3 } from "lucide-react";

export default function BorrowerAIScore() {
  const scoreFactors = [
    { factor: "Credit Matrix & Payment History", weight: "35%", status: "Excellent", score: "95/100", percent: 95 },
    { factor: "Income Stability & Revenue Ratio", weight: "25%", status: "Strong", score: "90/100", percent: 90 },
    { factor: "Debt-to-Income (DTI) Ratio", weight: "20%", status: "Healthy (18%)", score: "88/100", percent: 88 },
    { factor: "KYC Verification & Identity Matrix", weight: "20%", status: "Verified", score: "100/100", percent: 100 }
  ];

  return (
    <div className="space-y-6 font-sans text-slate-100 w-full max-w-7xl mx-auto pb-10 overflow-hidden">
      
      {/* 1. Header Banner */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-900 border border-slate-800 p-5 rounded-2xl shadow-lg">
        <div className="space-y-1">
          <div className="flex items-center gap-2 flex-wrap">
            <h1 className="text-xl font-bold tracking-tight text-white">AI Borrower Score (iNV IQ)</h1>
            <span className="px-2.5 py-0.5 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-[11px] font-bold rounded-full flex items-center gap-1">
              <Sparkles size={11} /> Wireframe Specs Compliant
            </span>
          </div>
          <p className="text-xs text-slate-400">
            Automated AI risk rating and qualification assessment generated by OAL's proprietary scoring model.
          </p>
        </div>
        <div className="flex items-center gap-2 px-3 py-1.5 bg-slate-950 border border-slate-800 rounded-xl text-xs text-emerald-400 font-semibold shrink-0 self-start sm:self-auto">
          <ShieldCheck size={16} /> Automated Read-Only Audit
        </div>
      </div>

      {/* 2. Main Score Hero Card */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 sm:p-8 flex flex-col md:flex-row items-center justify-between gap-8 relative overflow-hidden shadow-xl">
        <div className="absolute -right-10 -bottom-10 w-60 h-60 bg-indigo-600/10 rounded-full blur-3xl pointer-events-none"></div>

        <div className="space-y-4 max-w-xl text-center md:text-left">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-semibold rounded-full">
            <Cpu size={14} />
            iNV IQ AI Scoring Engine
          </div>

          <h2 className="text-2xl font-black text-white tracking-tight">Qualification Tier: Premium Investor</h2>

          <p className="text-xs text-slate-400 leading-relaxed">
            Your profile has been processed through our custom AI risk algorithm based on submitted loan requirements, verified financials, and credit history metrics.
          </p>

          <div className="flex flex-wrap items-center justify-center md:justify-start gap-4 text-xs font-semibold text-slate-300 pt-1">
            <span className="flex items-center gap-1.5 text-emerald-400">
              <CheckCircle2 size={16} /> Prime Qualified Applicant
            </span>
            <span className="flex items-center gap-1.5 text-indigo-400">
              <ShieldCheck size={16} /> Multi-Lender Waiting Room Access
            </span>
          </div>
        </div>

        {/* Score Badge Card */}
        <div className="p-6 bg-slate-950/90 border border-slate-800 rounded-2xl text-center space-y-2.5 min-w-[220px] shadow-2xl shrink-0">
          <span className="text-[11px] font-bold text-slate-400 uppercase tracking-widest block">AI Rating</span>
          <div className="text-6xl font-black text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-purple-400 to-emerald-400">
            A+
          </div>
          <p className="text-xs font-extrabold text-indigo-400 bg-indigo-500/10 px-3 py-1 rounded-full border border-indigo-500/20 inline-block">
            Score: 842 / 900
          </p>
          <p className="text-[11px] text-emerald-400 font-semibold pt-1">Low Risk Rating Profile</p>
        </div>
      </div>

      {/* 3. Factor Breakdown Grid */}
      <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 space-y-4 shadow-xl">
        <div className="flex items-center justify-between border-b border-slate-800 pb-3">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <BarChart3 size={18} className="text-indigo-400" />
            AI Score Factors Breakdown (iNV IQ Weights)
          </h3>
          <span className="text-xs text-slate-400 font-semibold">4 Key Metrics</span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {scoreFactors.map((item, idx) => (
            <div key={idx} className="p-4 bg-slate-950/70 border border-slate-850 rounded-xl space-y-2.5">
              <div className="flex justify-between items-center text-xs">
                <span className="font-bold text-white">{item.factor}</span>
                <span className="text-[11px] text-indigo-400 font-semibold">Weight: {item.weight}</span>
              </div>
              <div className="flex justify-between items-center text-xs">
                <span className="text-slate-400">Assessment: <strong className="text-emerald-400">{item.status}</strong></span>
                <span className="font-extrabold text-white">{item.score}</span>
              </div>
              <div className="w-full bg-slate-900 h-2 rounded-full overflow-hidden border border-slate-800">
                <div className="bg-gradient-to-r from-indigo-500 to-emerald-400 h-full rounded-full transition-all duration-700" style={{ width: `${item.percent}%` }}></div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* 4. Info Notice */}
      <div className="p-5 bg-slate-900 border border-slate-800 rounded-2xl flex items-start gap-3.5 shadow-md">
        <div className="p-2 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 rounded-xl shrink-0">
          <Info size={20} />
        </div>
        <div className="space-y-1 text-xs text-slate-400">
          <h4 className="font-bold text-white text-xs">How lenders view your AI Borrower Score</h4>
          <p className="leading-relaxed">
            Your AI Borrower Score is displayed anonymously to matched lenders in the Waiting Room marketplace. Higher scores allow lenders to offer lower interest rates and higher loan amounts for your application.
          </p>
        </div>
      </div>

    </div>
  );
}
