import React from "react";
import { Cpu, ShieldCheck, TrendingUp, AlertCircle, Info, CheckCircle2 } from "lucide-react";

export default function BorrowerAIScore() {
  const scoreFactors = [
    { factor: "Credit Matrix & Payment History", weight: "35%", status: "Excellent", score: "95/100" },
    { factor: "Income Stability & Revenue Ratio", weight: "25%", status: "Strong", score: "90/100" },
    { factor: "Debt-to-Income (DTI) Ratio", weight: "20%", status: "Healthy (18%)", score: "88/100" },
    { factor: "KYC Verification & Identity Matrix", weight: "20%", status: "Verified", score: "100/100" }
  ];

  return (
    <div className="space-y-6 font-sans text-slate-100 max-w-4xl">
      <div>
        <h1 className="text-2xl font-bold tracking-tight text-white">AI Borrower Score (iNV IQ)</h1>
        <p className="text-sm text-slate-400">Automated AI risk rating and qualification assessment generated by OAL's proprietary scoring model.</p>
      </div>

      {/* Main Score Hero Card */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-8 flex flex-col md:flex-row items-center justify-between gap-8 relative overflow-hidden">
        <div className="absolute -right-10 -bottom-10 w-60 h-60 bg-indigo-600/10 rounded-full blur-3xl pointer-events-none"></div>

        <div className="space-y-4 max-w-lg text-center md:text-left">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-semibold rounded-full">
            <Cpu size={14} />
            iNV IQ AI Scoring Engine
          </div>

          <h2 className="text-2xl font-extrabold text-white">Qualification Tier: Premium Investor</h2>

          <p className="text-xs text-slate-400 leading-relaxed">
            Your profile has been processed through our custom AI risk algorithm based on submitted loan requirements, verified financials, and credit history metrics.
          </p>

          <div className="flex flex-wrap items-center justify-center md:justify-start gap-4 text-xs font-semibold text-slate-300 pt-2">
            <span className="flex items-center gap-1.5 text-emerald-400">
              <CheckCircle2 size={16} /> Prime Qualified
            </span>
            <span className="flex items-center gap-1.5 text-indigo-400">
              <ShieldCheck size={16} /> Multi-Lender Match
            </span>
          </div>
        </div>

        {/* Score Badge */}
        <div className="p-6 bg-slate-950/80 border border-slate-800 rounded-2xl text-center space-y-2 min-w-[200px] shadow-xl">
          <span className="text-xs font-bold text-slate-500 uppercase tracking-widest block">AI Rating</span>
          <div className="text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 via-purple-400 to-emerald-400">
            A+
          </div>
          <p className="text-[11px] font-bold text-indigo-400 bg-indigo-500/10 px-2 py-0.5 rounded border border-indigo-500/20">
            Score: 842 / 900
          </p>
          <p className="text-[10px] text-slate-500 pt-1">Low Risk Profile</p>
        </div>
      </div>

      {/* Factor Breakdown Grid */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 space-y-4">
        <h3 className="text-base font-bold text-white border-b border-slate-800 pb-3 flex items-center gap-2">
          <TrendingUp size={18} className="text-indigo-400" />
          AI Score Factors Breakdown
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {scoreFactors.map((item, idx) => (
            <div key={idx} className="p-4 bg-slate-950/60 border border-slate-850 rounded-xl space-y-2">
              <div className="flex justify-between items-center">
                <span className="text-xs font-bold text-slate-200">{item.factor}</span>
                <span className="text-[10px] text-slate-500 font-mono">Weight: {item.weight}</span>
              </div>
              <div className="flex justify-between items-center text-xs">
                <span className="text-slate-400">Assessment: <strong className="text-emerald-400">{item.status}</strong></span>
                <span className="font-bold text-indigo-400">{item.score}</span>
              </div>
              <div className="w-full bg-slate-800 h-1.5 rounded-full overflow-hidden">
                <div className="bg-indigo-500 h-full rounded-full" style={{ width: item.score.split('/')[0] + '%' }}></div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Info Notice */}
      <div className="p-4 bg-slate-900/60 border border-slate-800 rounded-xl flex items-start gap-3">
        <Info size={20} className="text-indigo-400 shrink-0 mt-0.5" />
        <div className="space-y-1 text-xs text-slate-400">
          <h4 className="font-bold text-slate-200">How lenders view your score</h4>
          <p>
            Your AI Borrower Score is displayed anonymously to matched lenders on the OAL Network Marketplace. Higher scores allow lenders to offer lower interest rates and higher loan amounts.
          </p>
        </div>
      </div>
    </div>
  );
}
